### PR TITLE
Adding composer

### PR DESCRIPTION
**Pull request by elliotchance**
Composer is the default package manager for PHP. Once merged you can register the package at `packagist.org`.

I realise this is a very old package that is unlikely to change however it is best practice to create a `v1.0.0` tag, rather than consumers relying on your `master` branch being stable.

[Review on Reviewable](https://reviewable.io/reviews/rjmetrics/referral-grabber-php/1)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rjmetrics/referral-grabber-php/1)_

**Comment by elliotchance** [comment]
Is there any update on this?

**Comment by g-k** [comment]
Thanks for the PR!

@cmerrick says the methodology this package uses is deprecated, so we probably won't tag and publish it to packagist, but you can install from the repo using a commit hash: https://getcomposer.org/doc/04-schema.md#package-links

**Comment by elliotchance** [comment]
If this package is now deprecated, what should we use to replace it?

**Comment by cmerrick** [comment]
I added a note to the README that this library does not work with GA Universal Analytics.  I don't believe a drop-in replacement is possible as GA no longer makes this information available in a cookie.  This library looks like a promising alternative that creates the cookie for you, though I have not used it myself: https://github.com/alexfedoseev/sourcebuster-js

**Pull request merged**
